from tkinter import *
root=Tk()
root.title("Welcome to IoT")
root.geometry('500x300')
NameL= Label(root,text='Name: ')
NameL.grid(column=0,row=1)
numL= Label(root,text='Number: ')
numL.grid(column=0,row=2)
txt_field1= Entry(root,width=20)
txt_field1. grid(column=1,row=1)
txt_field2= Entry(root,width=20)
txt_field2. grid(column=1,row=2)
lb1= Label()
lb1.grid(column=5,row=1)
lb2=Label()
lb2.grid(column=5,row=2)
def clicked():
    res="You wrote "+txt_field1.get()
    lb1.configure(text=res)
    rs="Your number "+txt_field2.get()
    lb2.configure(text=rs)
def reset():
    txt_field1.delete(0,END)
    txt_field2.delete(0,END)
    lb1.configure(text='')
    lb2.configure(text='')
submit=Button(root,text='Submit',fg='red',command=clicked)
submit.grid(column=3,row=4)
reset=Button(root,text='Reset',fg='green',command=reset)
reset.grid(column=4,row=4)
root.mainloop()